name: Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_API_TOKEN }}
      - name: Publish
        run: |
          touch .env
          echo "MONGO_URL=${{ secrets.MONGO_URL }}" >> .env
          ls
          doctl serverless install
          doctl auth init \
            -t ${{ secrets.DIGITALOCEAN_API_TOKEN }}
          doctl serverless connect ${{ vars.DIGITALOCEAN_LABEL }} \
            -t ${{ secrets.DIGITALOCEAN_API_TOKEN }}
          doctl serverless deploy .
          doctl serverless functions invoke books/getBookByIsbn
